### ISSUE TITLE
fragment view doesnt recreate

### ISSUE THREAD

**Issue by jemmyphan** [smart-fun/TabStacker#1]
when im navigating back from another activity, the fragment view isn't recreate

**Comment by smart-fun** [comment]
Hello Jemmy and thank you for using TabStacker!

You are right, there was an issue when restoring the fragments after a startActivity was called. Sorry about that.

I drafted a new release (1.0.1) with the fix.

Could you please use it and tell me if that fixes your problem and there is no other problem with it? So that I can release that build for everyone ?

thank you!

Arnaud.

**Comment by jemmyphan** [comment]
it's working now, thanks for your quick response, it is definitely an awesome lib.

**Comment by smart-fun** [comment]
Thanks ^^
