### ISSUE TITLE
Tab Blank after dim screen

### ISSUE THREAD

**Issue by saifudin** [smart-fun/TabStacker#2]
Why Tab fragment blank after dim/off screen? what should i do to load the fragment again?
thanks

**Comment by sandeeprana011** [comment]
Same problem with me. TabStack cann't regain the same state after loosing focus from the activity.

**Comment by smart-fun** [comment]
Hello and thank you for using TabStacker.

Are you using release 1.0.1? Because I have done a fix that seems to be the same as yours.

If not, could you please describes the steps so that I can reproduce it? (I tried but cannot).
Do you reproduce it with the sample app (still 1.0.1 release)?
thank you!
Arnaud.

**Comment by sandeeprana011** [comment]
@smart-fun Thank you I just find the solution in another issue #1 .
This issue can be closed.

**Comment by saifudin** [comment]
woah.. sorry, the sample (1.0.1) is ok.  so the problem from my complicated code. sorry and thanks for this TabStacker.
