### ISSUE TITLE
No Callback for on Tab Reselect

### ISSUE THREAD

**Issue by sandeeprana011** [smart-fun/TabStacker#3]
I didn't find any callback like on Tab Reselect.

**Comment by smart-fun** [comment]
Hello,
in which case exactly do you need this callback called?

FYI there is onTabFragmentPresented(TabStacker.PresentReason reason) that is called when a new fragment is created (reason == NEW_FRAGMENT) and when the stack is restored (reason ==RESTORING_STACK), for example if you click on a tab that was previously displayed.

**Comment by sandeeprana011** [comment]
Suppose I am on the same tab and I selected it again then I want to clear the stack. 
And I want to be landed on the Home screen of that stack.

**Comment by smart-fun** [comment]
I have made a new pre-release **1.0.2**, could you please try to use it?

I have added a new method called **popToTop()**. Its purpose is to remove all the fragments except the 1st one.

So when you click on a tab, use it like this:

```
String tabName = clickedTab.name();

if (mTabStacker.getCurrentTabName().equals(tabName)) {  // Already the correct Stack, pop all but 1st fragment
    mTabStacker.popToTop(true); // true to force instant pop
} else {
    if (!mTabStacker.switchToTab(tabName)) {    // switch to the new Tab Stack
        // the stack is empty -> push the 1st fragment to the stack
        MyFragment fragment = createFragment();
        mTabStacker.replaceFragment(fragment, null);
    }
}
```

Tell me if this works for you and don't see any issue with it, so that I can release this version officially.

Thanks,

Arnaud.

**Comment by sandeeprana011** [comment]
Thanks @smart-fun 
It is working fine. 
If any issue occurs i will reopen the issue.
and special thanks for tab-stalker
