### ISSUE TITLE
my UI hang / freeze when add new fragment with ScrollView inside

### ISSUE THREAD

**Issue by saifudin** [smart-fun/TabStacker#5]
sorry for ask again, 
why my UI hang when add new fragment with ScrollView inside? 
any idea what should i do?
thanks
ifud

**Comment by smart-fun** [comment]
Hello
tabStacker makes no difference between a fragment with or without a scrollview inside. It is more likely the setup of your fragment which takes time. Is the app completely frozen forever? Is there a place where I can have a look to your code ?
Just to let you know, ListView is like "old fashion" for lists, I prefer using RecyclerView. But changing to RecyclerView probably will NOT solve your problem ;)

**Comment by saifudin** [comment]
yeah. i guess this is fragment problem. 
i try to give a ProgressBar during fragment transaction but the ProgressBar frozen
no spesial or complicated code. i just give alot TextView, EditText for collect user data inside scrollview for the next fragment. 
any idea to give a ProgressBar during fragment transaction without frozen ProgressBar ? :D

**Comment by saifudin** [comment]
"Is the app completely frozen forever?"
No. just some second before next fragment presented.

**Comment by smart-fun** [comment]
If you collect a lot of data in the main thread, it explains why the app is not responding for a few seconds. You should try to use AsyncTask or Thread to do this in a background task so that the UI is still alive. For example with AsyncTask you can do the hard job in doInBackground() and when it is finished you update the UI from onPostExecute().
Without seeing your code it is hard to guess what is happening ;)
If you are sure that the issue does not come from tabStacker please close this issue.

**Comment by saifudin** [comment]
hmmm.. ok sorry..
