### ISSUE TITLE
Rotation resets fragment backstack

### ISSUE THREAD

**Issue by Chrylo** [smart-fun/TabStacker#8]
Hi there! If you add/replace some fragments and then rotate the phone, the fragment back stack is not being restored. Is this intended?

**Comment by smart-fun** [comment]
Hello Mark,

sorry for the late answer, I was in vacation ^^

No this is not the expected behaviour. I just tested the last version of the sample app and you are right, it is no more restored after device rotation. I guess I introduced this issue while fixing another bug. I will have to investigate but I am not very available for that this week. I tell you as soon as I can.

Arnaud.

**Comment by smart-fun** [comment]
Hello again,

I looked into the problem and it was just a mistake in the sample app, not in the library. I just fixed it and published a release 1.0.3.

Could you please try this one and tell me if everything is ok?

thanks again,

Arnaud.

**Comment by Chrylo** [comment]
Hi Arnaud, seems to work. ;)

I will close the issue after some more testing.

It would be awesome if this library would support material transitions (content transitions) for non support v4 fragments. But that's probably too much to ask. :>

Thanks anyway for the library.
Mark

**Comment by smart-fun** [comment]
This is a good idea to support content transitions! But I would probably do that on support fragments.
I will do some tests...
Arnaud.
